name: sheriff
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sheriff:
    runs-on: ubuntu-latest
    env:
      ENV: tests
      PSQL_USER: postgres
      PSQL_PASSWORD: postgres
      PSQL_DATABASE: sheriff

    services:
      postgres:
        image: postgres:latest

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sheriff

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./ts/package-lock.json

      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "7.x"

      - name: install deps nodejs
        working-directory: ./ts
        run: |
          npm install

      - name: eslint nodejs
        working-directory: ./ts
        run: npm run lint

      - name: runs migrations
        working-directory: ./ts
        run: npm run migrate:latest

      - name: runs tests
        working-directory: ./ts
        run: npm test 
